### ISSUE TITLE
Trouble sync-on-save with two different repos in the same project

### ISSUE THREAD

**Issue by gammacray** [omo/sync-on-save#12]
I've been working with your package for a couple months and it works great so far, but today I opened a new repo/project within the same session and now sync-on-save works for the one I've had open for a couple months, but doesn't work at all for the new repo?

I've tried enable/disable/start syncing in every way I can think of. Is there something I'm missing?

Thanks.

**Comment by omo** [comment]
Sorry, but I'm not working on this anymore.
If you have a proposed change, I'm happy to accept.

**Comment by gammacray** [comment]
It's taken me awhile to get back to you, thanks for responding. Honestly for what I'm doing I think it works better to have separate projects in separate instances of atom anyhow. So my issue is closed. 

I really appreciate your package. It saves so much time. Thanks!
